### ISSUE TITLE
plotting SRScruve without lty raises an error, consider adding defaults

### ISSUE THREAD

**Issue by mestaki** [vitorheidrich/q2-srs#3]
Hello,

Getting around to finally playing this cool method you've developed!
Just a minor suggestion that maybe `lty` parameter should have some defaults if the user doesn't provide them. Currently it completes but fails to plot a legend without it and raises a warning/error.

ex using the data from manual:
```
example_input_data <- matrix(c(sample(1:20, 100, replace = TRUE),
sample(1:30, 100, replace = TRUE),sample(1:40, 100, replace = TRUE)), nrow = 100)
colnames(example_input_data) <- c("sample_1","sample_2","sample_3")
example_input_data <- as.data.frame(example_input_data)
example_input_data
```
Plot SRScurve without ltype

```
SRScurve(example_input_data, metric = "richness", step = 50,
         sample = 200, max.sample.size = 200,
         rarefy.comparison = TRUE, rarefy.repeats = 10, rarefy.comparison.legend = TRUE,
         ylab = "richness", 
         col = c(rep(c("#000000", "#E69F00", "#56B4E9"),2)))
```
raises this error:

```
Error in SRScurve(example_input_data, metric = "richness", step = 50,  : 
  object 'nltypes' not found
```
with the plot looking like:

![image](https://user-images.githubusercontent.com/17439092/105744530-232a3f80-5ef2-11eb-9728-6a37709afcc4.png)

SRS version: 0.2.1
Vegan version: 2.6.0

**Comment by vitorheidrich** [comment]
Hi,

Thank you very much for pointing this out! We've corrected the SRScurve implementation. The new version will be available in the next package update.

However, I must say that not plotting a legend in this case is the expected behavior for SRScurve. The only error was that (instead of `object 'nltypes' not found`) the following message should have appeared:

```
Warning message:
In SRScurve(example_input_data, metric = "richness", step = 50,  :
  rarefy.comparison.legend only works when exactly 2 colors ('col') and/or 2 line types ('lty') were chosen
```

The 'rarefy.comparison.legend' parameter is used to provide a legend in order to compare SRS curves and rarefaction curves (we are comparing the normalization methods, not samples), which will only work if the user has chosen exactly 2 colors and/or exactly 2 ltypes, because there are only 2 levels (SRS vs. rarefaction). So, in your test, you won't be able to compare SRS curves and rarefaction curves because they both (for a given sample) would have the same color and linetype, making, therefore, the legend meaningless.

Here follows three examples on how you could've combined 'col' and 'lty' to make 'rarefy.comparison.legend' show up properly (SRS version = 0.2.1):

```
SRScurve(example_input_data, metric = "richness", step = 50,
         sample = 200, max.sample.size = 200,
         rarefy.comparison = TRUE, rarefy.repeats = 10, rarefy.comparison.legend = TRUE,
         ylab = "richness", 
         col = c("#000000", "#E69F00"))
```
![image](https://user-images.githubusercontent.com/72625631/105750087-035f3f80-5f23-11eb-93c7-b10241d8fe49.png)
```
SRScurve(example_input_data, metric = "richness", step = 50,
         sample = 200, max.sample.size = 200,
         rarefy.comparison = TRUE, rarefy.repeats = 10, rarefy.comparison.legend = TRUE,
         ylab = "richness", 
         col = c("#000000", "#E69F00"), lty = c("solid","longdash"))
```
![image](https://user-images.githubusercontent.com/72625631/105750551-a44dfa80-5f23-11eb-8051-b6eb35b41f41.png)

```
SRScurve(example_input_data, metric = "richness", step = 50,
         sample = 200, max.sample.size = 200,
         rarefy.comparison = TRUE, rarefy.repeats = 10, rarefy.comparison.legend = TRUE,
         ylab = "richness", 
         col = c(rep(c("#000000", "#E69F00", "#56B4E9"),2)), lty = c("solid","longdash"))
```
![image](https://user-images.githubusercontent.com/72625631/105750213-39042880-5f23-11eb-8e21-c568859d45d7.png)

Please let me know whether my explanation was clear. Thanks again for your suggestion!

Cheers,

Vitor

**Comment by mestaki** [comment]
Hi @vitorheidrich ,
Thanks for clarifying, and the useful examples, that makes a lot more sense now. 
I have another comment/suggestion regarding the plots which I'll open a new issue for. 
Very cool work, looking forward to benchmarking it properly with some real data we have.
